# Summarize Data 기본통계하기

## value_counts, nunique, sum, count, mean, median

In [29]:
import pandas as pd
import seaborn as sns

import numpy as np

In [4]:
df = sns.load_dataset('iris')

# 150행, 5열의 데이터프레임을 알 수 있다. 
df.shape

(150, 5)

In [10]:
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
5             5.4          3.9           1.7          0.4     setosa
6             4.6          3.4           1.4          0.3     setosa
7             5.0          3.4           1.5          0.2     setosa
8             4.4          2.9           1.4          0.2     setosa
9             4.9          3.1           1.5          0.1     setosa
10            5.4          3.7           1.5          0.2     setosa
11            4.8          3.4           1.6          0.2     setosa
12            4.8          3.0           1.4          0.1     setosa
13            4.3          3.0           1.1          0.1     setosa
14            5.8          4.0           1.2          0.2     setosa
15            5.7          4.4           1.5          0.4     setosa
16            5.4          3.9           1.3          0.4     setosa
17            5.1          3.5           1.4          0.3     setosa
18            5.7          3.8           1.7          0.3     setosa
19            5.1          3.8           1.5          0.3     setosa
20            5.4          3.4           1.7          0.2     setosa
21            5.1          3.7           1.5          0.4     setosa
22            4.6          3.6           1.0          0.2     setosa
23            5.1          3.3           1.7          0.5     setosa
24            4.8          3.4           1.9          0.2     setosa
25            5.0          3.0           1.6          0.2     setosa
26            5.0          3.4           1.6          0.4     setosa
27            5.2          3.5           1.5          0.2     setosa
28            5.2          3.4           1.4          0.2     setosa
29            4.7          3.2           1.6          0.2     setosa
..            ...          ...           ...          ...        ...
120           6.9          3.2           5.7          2.3  virginica
121           5.6          2.8           4.9          2.0  virginica
122           7.7          2.8           6.7          2.0  virginica
123           6.3          2.7           4.9          1.8  virginica
124           6.7          3.3           5.7          2.1  virginica
125           7.2          3.2           6.0          1.8  virginica
126           6.2          2.8           4.8          1.8  virginica
127           6.1          3.0           4.9          1.8  virginica
128           6.4          2.8           5.6          2.1  virginica
129           7.2          3.0           5.8          1.6  virginica
130           7.4          2.8           6.1          1.9  virginica
131           7.9          3.8           6.4          2.0  virginica
132           6.4          2.8           5.6          2.2  virginica
133           6.3          2.8           5.1          1.5  virginica
134           6.1          2.6           5.6          1.4  virginica
135           7.7          3.0           6.1          2.3  virginica
136           6.3          3.4           5.6          2.4  virginica
137           6.4          3.1           5.5          1.8  virginica
138           6.0          3.0           4.8          1.8  virginica
139           6.9          3.1           5.4          2.1  virginica
140           6.7          3.1           5.6          2.4  virginica
141           6.9          3.1           5.1          2.3  virginica
142           5.8          2.7           5.1          1.9  virginica
143           6.8          3.2           5.9          2.3  virginica
144           6.7          3.3           5.7          2.5  virginica
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

### df['w'].value_counts()
- 각각의 값을 그룹화하여 개수를 세어준다.
- 숫자데이터보다는 종류들의 갱수를 세는데 있어서 적합하다. 어떤 값이 몇개 들어있는지 확인할때 유용.

In [9]:
df['species'].value_counts()

setosa        50
versicolor    50
virginica     50
Name: species, dtype: int64

In [11]:
df['petal_width'].value_counts()

0.2    29
1.3    13
1.5    12
1.8    12
1.4     8
2.3     8
1.0     7
0.3     7
0.4     7
2.0     6
2.1     6
0.1     5
1.2     5
1.9     5
1.6     4
2.5     3
2.2     3
2.4     3
1.1     3
1.7     2
0.6     1
0.5     1
Name: petal_width, dtype: int64

In [12]:
# value_counts를 만들어 따로 사용하고싶다면?
pd.DataFrame(df['species'].value_counts())

            species
setosa           50
versicolor       50
virginica        50

In [23]:
pd.DataFrame(df['sepal_width'].value_counts())

     sepal_width
3.0           26
2.8           14
3.2           13
3.4           12
3.1           11
2.9           10
2.7            9
2.5            8
3.5            6
3.8            6
3.3            6
2.6            5
2.3            4
3.6            4
2.4            3
2.2            3
3.7            3
3.9            2
4.2            1
4.1            1
4.4            1
2.0            1
4.0            1

### len(df)
- dataframe의 행이 몇개인지 세어준다.

In [13]:
# 150개의 행이 있음을 확인가능
len(df)

# 이는 df.shape(0)을 통해서도 동일하게 확인이 가능하다.

150

In [21]:
len(df) == df.shape[0]

True

### df['w'].nunique()
- w라는 이름의 컬럼의 고유한 값의 개수를 알려준다. (행요소들의 중복되지 않는 범위에서 개수)
- 이 unique value들이 몇개씩 있는지 세어보고싶다면 value_counts를 써보면 된다.

In [22]:
df['species'].nunique()

3

In [24]:
df['sepal_width'].nunique()

23

### df.describe()
- 기본적인 통계적 수치를 보여준다.
- 기본적으로 수치형 데이터에 대한 통계값들을 보여준다.

In [27]:
df.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [28]:
# 모든 데이터를 보고싶다면?
# include가 아닌 exclude를 사용하여 특정 데이터를 제외하여 보는 것도 가능
df.describe(include = 'all')

        sepal_length  sepal_width  petal_length  petal_width species
count     150.000000   150.000000    150.000000   150.000000     150
unique           NaN          NaN           NaN          NaN       3
top              NaN          NaN           NaN          NaN  setosa
freq             NaN          NaN           NaN          NaN      50
mean        5.843333     3.057333      3.758000     1.199333     NaN
std         0.828066     0.435866      1.765298     0.762238     NaN
min         4.300000     2.000000      1.000000     0.100000     NaN
25%         5.100000     2.800000      1.600000     0.300000     NaN
50%         5.800000     3.000000      4.350000     1.300000     NaN
75%         6.400000     3.300000      5.100000     1.800000     NaN
max         7.900000     4.400000      6.900000     2.500000     NaN

In [30]:
# object타입만 보고싶다면?
df.describe(include = [np.object])

       species
count      150
unique       3
top     setosa
freq        50

In [31]:
# count - 데이터가 몇개인지, mean - 평균값, std - 표준편차 를 보여준다.
# 이는 요약된 수치를 볼 수 있다. 
df.describe(include = [np.number])

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

``
sum()
Sum values of each object.
count()
Count non-NA/null values of
each object.
median()
Median value of each object.
quantile([0.25,0.75])
Quantiles of each object.
apply(function)
Apply function to each object.
min()
Minimum value in each object.
max()
Maximum value in each object.
mean()
Mean value of each object.
var()
Variance of each object.
std()
Standard deviation of each object.
``

In [32]:
# 전체값의 합계를 보여준다.
df['petal_width'].sum()

179.90000000000003

In [34]:
# 개수
df['petal_width'].count()

150

In [36]:
# 중간값
df['petal_width'].median()

1.3

In [35]:
# 평균값
df['petal_width'].mean()

1.199333333333334

In [38]:
# 25~75퍼 사이에 있는 수
df.quantile([0.25, 0.75])

      sepal_length  sepal_width  petal_length  petal_width
0.25           5.1          2.8           1.6          0.3
0.75           6.4          3.3           5.1          1.8

In [40]:
# quantile에서는 df[]로 특정 컬럼을 지정하여 볼 수도 있다.
df['petal_width'].quantile([0.25, 0.75])

0.25    0.3
0.75    1.8
Name: petal_width, dtype: float64

In [41]:
# 각각의 컬럼의 최소값 보자
df.min()

sepal_length       4.3
sepal_width          2
petal_length         1
petal_width        0.1
species         setosa
dtype: object

In [42]:
# 각각의 컬럼의 최대값
df.max()

sepal_length          7.9
sepal_width           4.4
petal_length          6.9
petal_width           2.5
species         virginica
dtype: object

In [43]:
# 분산
df.var()

sepal_length    0.685694
sepal_width     0.189979
petal_length    3.116278
petal_width     0.581006
dtype: float64

In [44]:
# 표준편차
df.std()

sepal_length    0.828066
sepal_width     0.435866
petal_length    1.765298
petal_width     0.762238
dtype: float64

## pandas로 apply활용하기, lambda 익명함수 사용하기

### apply(function)
- 데이터 전처리에 있어서 유용하다.

In [45]:
df.apply?

In [46]:
# 익명함수 lambda
# 데이터를 처리할때 이러한 익명함수 lambda를 사용하기도 한다.
df.apply(lambda x : x)

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
5             5.4          3.9           1.7          0.4     setosa
6             4.6          3.4           1.4          0.3     setosa
7             5.0          3.4           1.5          0.2     setosa
8             4.4          2.9           1.4          0.2     setosa
9             4.9          3.1           1.5          0.1     setosa
10            5.4          3.7           1.5          0.2     setosa
11            4.8          3.4           1.6          0.2     setosa
12            4.8          3.0           1.4          0.1     setosa
13            4.3          3.0           1.1          0.1     setosa
14            5.8          4.0           1.2          0.2     setosa
15            5.7          4.4           1.5          0.4     setosa
16            5.4          3.9           1.3          0.4     setosa
17            5.1          3.5           1.4          0.3     setosa
18            5.7          3.8           1.7          0.3     setosa
19            5.1          3.8           1.5          0.3     setosa
20            5.4          3.4           1.7          0.2     setosa
21            5.1          3.7           1.5          0.4     setosa
22            4.6          3.6           1.0          0.2     setosa
23            5.1          3.3           1.7          0.5     setosa
24            4.8          3.4           1.9          0.2     setosa
25            5.0          3.0           1.6          0.2     setosa
26            5.0          3.4           1.6          0.4     setosa
27            5.2          3.5           1.5          0.2     setosa
28            5.2          3.4           1.4          0.2     setosa
29            4.7          3.2           1.6          0.2     setosa
..            ...          ...           ...          ...        ...
120           6.9          3.2           5.7          2.3  virginica
121           5.6          2.8           4.9          2.0  virginica
122           7.7          2.8           6.7          2.0  virginica
123           6.3          2.7           4.9          1.8  virginica
124           6.7          3.3           5.7          2.1  virginica
125           7.2          3.2           6.0          1.8  virginica
126           6.2          2.8           4.8          1.8  virginica
127           6.1          3.0           4.9          1.8  virginica
128           6.4          2.8           5.6          2.1  virginica
129           7.2          3.0           5.8          1.6  virginica
130           7.4          2.8           6.1          1.9  virginica
131           7.9          3.8           6.4          2.0  virginica
132           6.4          2.8           5.6          2.2  virginica
133           6.3          2.8           5.1          1.5  virginica
134           6.1          2.6           5.6          1.4  virginica
135           7.7          3.0           6.1          2.3  virginica
136           6.3          3.4           5.6          2.4  virginica
137           6.4          3.1           5.5          1.8  virginica
138           6.0          3.0           4.8          1.8  virginica
139           6.9          3.1           5.4          2.1  virginica
140           6.7          3.1           5.6          2.4  virginica
141           6.9          3.1           5.1          2.3  virginica
142           5.8          2.7           5.1          1.9  virginica
143           6.8          3.2           5.9          2.3  virginica
144           6.7          3.3           5.7          2.5  virginica
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [49]:
print(df.apply(lambda x : x[0]), end="\n\n\n")
print(df.apply(lambda x : x[1]), end="\n\n\n")
print(df.apply(lambda x : x[2]))

sepal_length       5.1
sepal_width        3.5
petal_length       1.4
petal_width        0.2
species         setosa
dtype: object


sepal_length       4.9
sepal_width          3
petal_length       1.4
petal_width        0.2
species         setosa
dtype: object


sepal_length       4.7
sepal_width        3.2
petal_length       1.3
petal_width        0.2
species         setosa
dtype: object

In [52]:
# species컬럼에서 0번째항..세번째 글자까지 가져올 수 있다.
df['species'].apply(lambda x : x[:3]).head()

0    set
1    set
2    set
3    set
4    set
Name: species, dtype: object

In [55]:
# 따로 컬럼을 만들어 값을 넣어주는 것도 가능하다. 
df['species_3'] = df['species'].apply(lambda x : x[:3])
df

     sepal_length  sepal_width  petal_length  petal_width    species species_3
0             5.1          3.5           1.4          0.2     setosa       set
1             4.9          3.0           1.4          0.2     setosa       set
2             4.7          3.2           1.3          0.2     setosa       set
3             4.6          3.1           1.5          0.2     setosa       set
4             5.0          3.6           1.4          0.2     setosa       set
5             5.4          3.9           1.7          0.4     setosa       set
6             4.6          3.4           1.4          0.3     setosa       set
7             5.0          3.4           1.5          0.2     setosa       set
8             4.4          2.9           1.4          0.2     setosa       set
9             4.9          3.1           1.5          0.1     setosa       set
10            5.4          3.7           1.5          0.2     setosa       set
11            4.8          3.4           1.6          0.2     setosa       set
12            4.8          3.0           1.4          0.1     setosa       set
13            4.3          3.0           1.1          0.1     setosa       set
14            5.8          4.0           1.2          0.2     setosa       set
15            5.7          4.4           1.5          0.4     setosa       set
16            5.4          3.9           1.3          0.4     setosa       set
17            5.1          3.5           1.4          0.3     setosa       set
18            5.7          3.8           1.7          0.3     setosa       set
19            5.1          3.8           1.5          0.3     setosa       set
20            5.4          3.4           1.7          0.2     setosa       set
21            5.1          3.7           1.5          0.4     setosa       set
22            4.6          3.6           1.0          0.2     setosa       set
23            5.1          3.3           1.7          0.5     setosa       set
24            4.8          3.4           1.9          0.2     setosa       set
25            5.0          3.0           1.6          0.2     setosa       set
26            5.0          3.4           1.6          0.4     setosa       set
27            5.2          3.5           1.5          0.2     setosa       set
28            5.2          3.4           1.4          0.2     setosa       set
29            4.7          3.2           1.6          0.2     setosa       set
..            ...          ...           ...          ...        ...       ...
120           6.9          3.2           5.7          2.3  virginica       vir
121           5.6          2.8           4.9          2.0  virginica       vir
122           7.7          2.8           6.7          2.0  virginica       vir
123           6.3          2.7           4.9          1.8  virginica       vir
124           6.7          3.3           5.7          2.1  virginica       vir
125           7.2          3.2           6.0          1.8  virginica       vir
126           6.2          2.8           4.8          1.8  virginica       vir
127           6.1          3.0           4.9          1.8  virginica       vir
128           6.4          2.8           5.6          2.1  virginica       vir
129           7.2          3.0           5.8          1.6  virginica       vir
130           7.4          2.8           6.1          1.9  virginica       vir
131           7.9          3.8           6.4          2.0  virginica       vir
132           6.4          2.8           5.6          2.2  virginica       vir
133           6.3          2.8           5.1          1.5  virginica       vir
134           6.1          2.6           5.6          1.4  virginica       vir
135           7.7          3.0           6.1          2.3  virginica       vir
136           6.3          3.4           5.6          2.4  virginica       vir
137           6.4          3.1           5.5          1.8  virginica       vir
138           6.0          3.0           4.8          1.8  virginica       vir
139           6.9          3.1           5.4          2.1  virginica       vir
140           6.7          3.1           5.6          2.4  virginica       vir
141           6.9          3.1           5.1          2.3  virginica       vir
142           5.8          2.7           5.1          1.9  virginica       vir
143           6.8          3.2           5.9          2.3  virginica       vir
144           6.7          3.3           5.7          2.5  virginica       vir
145           6.7          3.0           5.2          2.3  virginica       vir
146           6.3          2.5           5.0          1.9  virginica       vir
147           6.5          3.0           5.2          2.0  virginica       vir
148           6.2          3.4           5.4          2.3  virginica       vir
149           5.9          3.0           5.1          1.8  virginica       vir

[150 rows x 6 columns]

In [56]:
# 함수를 아예 새로만들어보자
def smp(x) : # sample의 약자 smp
    # 뒤에서 3번째 까지의 문자를 가져오는 함수
    x = x[:-3] # 뒤에서 세번째 값을 가져오자
    return x

In [58]:
df['species-3'] = df['species'].apply(smp)
df

,sepal_length,sepal_width,petal_length,petal_width,species,species_3,species-3
0,5.1,3.5,1.4,0.2,setosa,set,set
1,4.9,3.0,1.4,0.2,setosa,set,set
2,4.7,3.2,1.3,0.2,setosa,set,set
3,4.6,3.1,1.5,0.2,setosa,set,set
4,5.0,3.6,1.4,0.2,setosa,set,set
5,5.4,3.9,1.7,0.4,setosa,set,set
6,4.6,3.4,1.4,0.3,setosa,set,set
7,5.0,3.4,1.5,0.2,setosa,set,set
8,4.4,2.9,1.4,0.2,setosa,set,set
9,4.9,3.1,1.5,0.1,setosa,set,set
10,5.4,3.7,1.5,0.2,setosa,set,set
11,4.8,3.4,1.6,0.2,setosa,set,set
12,4.8,3.0,1.4,0.1,setosa,set,set
13,4.3,3.0,1.1,0.1,setosa,set,set
14,5.8,4.0,1.2,0.2,setosa,set,set
15,5.7,4.4,1.5,0.4,setosa,set,set
16,5.4,3.9,1.3,0.4,setosa,set,set
17,5.1,3.5,1.4,0.3,setosa,set,set
18,5.7,3.8,1.7,0.3,setosa,set,set
19,5.1,3.8,1.5,0.3,setosa,set,set
20,5.4,3.4,1.7,0.2,setosa,set,set
21,5.1,3.7,1.5,0.4,setosa,set,set
22,4.6,3.6,1.0,0.2,setosa,set,set
23,5.1,3.3,1.7,0.5,setosa,set,set
24,4.8,3.4,1.9,0.2,setosa,set,set
25,5.0,3.0,1.6,0.2,setosa,set,set
26,5.0,3.4,1.6,0.4,setosa,set,set
27,5.2,3.5,1.5,0.2,setosa,set,set
28,5.2,3.4,1.4,0.2,setosa,set,set
29,4.7,3.2,1.6,0.2,setosa,set,set
...,...,...,...,...,...,...,...
120,6.9,3.2,5.7,2.3,virginica,vir,virgin
121,5.6,2.8,4.9,2.0,virginica,vir,virgin
122,7.7,2.8,6.7,2.0,virginica,vir,virgin
123,6.3,2.7,4.9,1.8,virginica,vir,virgin
124,6.7,3.3,5.7,2.1,virginica,vir,virgin
125,7.2,3.2,6.0,1.8,virginica,vir,virgin
126,6.2,2.8,4.8,1.8,virginica,vir,virgin
127,6.1,3.0,4.9,1.8,virginica,vir,virgin
128,6.4,2.8,5.6,2.1,virginica,vir,virgin
129,7.2,3.0,5.8,1.6,virginica,vir,virgin
130,7.4,2.8,6.1,1.9,virginica,vir,virgin
131,7.9,3.8,6.4,2.0,virginica,vir,virgin
132,6.4,2.8,5.6,2.2,virginica,vir,virgin
133,6.3,2.8,5.1,1.5,virginica,vir,virgin
134,6.1,2.6,5.6,1.4,virginica,vir,virgin
135,7.7,3.0,6.1,2.3,virginica,vir,virgin
136,6.3,3.4,5.6,2.4,virginica,vir,virgin
137,6.4,3.1,5.5,1.8,virginica,vir,virgin
138,6.0,3.0,4.8,1.8,virginica,vir,virgin
139,6.9,3.1,5.4,2.1,virginica,vir,virgin
140,6.7,3.1,5.6,2.4,virginica,vir,virgin
141,6.9,3.1,5.1,2.3,virginica,vir,virgin
142,5.8,2.7,5.1,1.9,virginica,vir,virgin
143,6.8,3.2,5.9,2.3,virginica,vir,virgin
144,6.7,3.3,5.7,2.5,virginica,vir,virgin
145,6.7,3.0,5.2,2.3,virginica,vir,virgin
146,6.3,2.5,5.0,1.9,virginica,vir,virgin
147,6.5,3.0,5.2,2.0,virginica,vir,virgin
148,6.2,3.4,5.4,2.3,virginica,vir,virgin
149,5.9,3.0,5.1,1.8,virginica,vir,virgin

## 따라서 apply()함수를 사용할때
- 1. lambada 다음에 익명함수를 사용해도 되고

```python
df['species_3'] = df['species'].apply(lambda x : x[:3])
```

- 2. 그 전에 외부에다가 함수를 하나 만들어서 호출하여 사용해도 된다.

```python
def smp(x) :
    # 뒤에서 3번째 까지의 문자를 가져오는 함수
    x = x[:-3]
    return x

df['species-3'] = df['species'].apply(smp)
```